### PR TITLE
dark mode

### PR DESCRIPTION
**Pull request by Nightwing000**
wasn't able to test using your css files since it gave MIME errors on my side so I used css in the html files and just switched text and background colors.

### CODE REVIEW

**Comment by rohancyriac029** [comment]
@Nightwing000 can you send me a screenshot after you login where have you added the dark/light toggler
and the appointment page is not linked yet i think i dont see the change in app.py

**Comment by Nightwing000** [comment]
I haven't changed anything in the python files. I took it as a css issue and implemented a button(same everything in both html files) 
image
image

**Comment by rohancyriac029** [comment]
@Nightwing000 you need to run that ask a flask file and the change was supposed to be in that and linking the appointments page was also a part of the question what you have done does not address most of these things
Screenshot 2024-10-19 054407

**Comment by rohancyriac029** [comment]
For what you have done I cannot give you the full bounty at all even other maintainers have said the same.

**Comment by rohancyriac029** [comment]
!bounty 10

**Comment by Nightwing000** [comment]
yeah that's fair thanks a lot

**Pull request closed without merging**
