### PR TITLE
Captcha added

### PR DESCRIPTION
**Pull request by mahika34**
I have added a captcha on the top of signup page.
Please check and assign some bounty points

### CODE REVIEW

**Comment by rohancyriac029** [comment]
@mahika34 let me check and get back to you in a few minutes

**Comment by mahika34** [comment]
yeah sure!

**Comment by rohancyriac029** [comment]
@mahika34 have you added all of these changes youve made in a templates folder?

**Comment by mahika34** [comment]
yes i have added the css and js files

**Comment by rohancyriac029** [comment]
can you send me a screenshot of how it looks in your screen cause it is not giving a proper output for me like even it being on top of the signup page is wrong but no captcha shows up

**Comment by mahika34** [comment]
image

umm it should give the captcha also. It came before but now its not coming. Maybe cuz of internet issue

**Comment by mahika34** [comment]
yeah i mentioned that i put it in the top of the page

**Comment by rohancyriac029** [comment]
There is some issue with your api call Ive asked some of the other maintainer heads to assign you even partial bounty you need to get get the captcha working in the least

**Comment by mahika34** [comment]
ohk ill try

**Pull request closed without merging**
